#!/usr/bin/env node
/**
 * Derives src/generated/schema.postgres.prisma from prisma/schema.prisma.
 *
 * The app is developed against SQLite, but can also run on PostgreSQL (e.g. Neon or Prisma
 * Postgres connected through Vercel). Both Prisma clients are generated from the same models,
 * so there is a single schema to maintain; only the provider and output folder differ.
 * Runs as part of `db:generate` (and therefore on install); src/generated/ is git-ignored.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const serverRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = readFileSync(path.join(serverRoot, 'prisma', 'schema.prisma'), 'utf8');

const replaceOnce = (text, pattern, replacement, label) => {
  if (!pattern.test(text))
    throw new Error(`postgres-schema: could not find ${label} in prisma/schema.prisma`);
  return text.replace(pattern, replacement);
};

let schema = replaceOnce(
  source,
  /provider\s*=\s*"sqlite"/,
  'provider = "postgresql"',
  'the sqlite provider',
);
// The generated schema lives in src/generated/, so the client goes next to it.
schema = replaceOnce(
  schema,
  /output\s*=\s*"\.\.\/src\/generated\/prisma"/,
  'output = "./prisma-postgres"',
  'the client output path',
);

const header =
  '// Generated by scripts/postgres-schema.mjs from prisma/schema.prisma - do not edit.\n';
const outFile = path.join(serverRoot, 'src', 'generated', 'schema.postgres.prisma');
mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, header + schema, 'utf8');
console.log('Wrote src/generated/schema.postgres.prisma');
